// Mock data for content management — used across lesson-management, learning-path, content-approval

import {
  ContentSubmission,
  CurriculumItem,
  Lesson,
  LearningPath,
} from '@/types/content.types';

// ─── Lessons ──────────────────────────────────────────────────────────────────
export const MOCK_LESSONS: Lesson[] = [
  {
    id: 'L001',
    title: 'Tư thế cầm sáo đúng cách',
    description:
      'Hướng dẫn chi tiết về cách cầm sáo, đặt ngón tay và tư thế cơ thể khi thổi sáo.',
    type: 'video',
    level: 'beginner',
    status: 'published',
    duration: 12,
    author: 'GV. Minh Tú',
    authorEmail: 'minhtu@lenfolk.vn',
    tags: ['căn bản', 'tư thế', 'kỹ thuật'],
    viewCount: 1842,
    completionRate: 78,
    pathId: 'P001',
    pathTitle: 'Nhập môn sáo trúc',
    createdAt: '2026-03-01',
    updatedAt: '2026-04-10',
  },
  {
    id: 'L002',
    title: 'Kỹ thuật thổi hơi cơ bản',
    description: 'Bài học về cách kiểm soát hơi thở và lực thổi khi chơi sáo.',
    type: 'video',
    level: 'beginner',
    status: 'published',
    duration: 18,
    author: 'GV. Thu Hà',
    authorEmail: 'thuha@lenfolk.vn',
    tags: ['hơi thổi', 'căn bản'],
    viewCount: 1520,
    completionRate: 72,
    pathId: 'P001',
    pathTitle: 'Nhập môn sáo trúc',
    createdAt: '2026-03-05',
    updatedAt: '2026-04-15',
  },
  {
    id: 'L003',
    title: 'Láy hơi – kỹ thuật nâng cao',
    description:
      'Kỹ thuật láy hơi, rung hơi và các phương pháp tạo âm sắc đặc trưng.',
    type: 'video',
    level: 'advanced',
    status: 'published',
    duration: 25,
    author: 'GV. Minh Tú',
    authorEmail: 'minhtu@lenfolk.vn',
    tags: ['nâng cao', 'láy hơi', 'âm sắc'],
    viewCount: 842,
    completionRate: 61,
    pathId: 'P003',
    pathTitle: 'Kỹ thuật nâng cao',
    createdAt: '2026-03-20',
    updatedAt: '2026-05-01',
  },
  {
    id: 'L004',
    title: 'Bài tập ngón tay số 1',
    description: 'Các bài tập luyện ngón tay linh hoạt cho người mới bắt đầu.',
    type: 'exercise',
    level: 'beginner',
    status: 'published',
    duration: 10,
    author: 'GV. Đức Anh',
    authorEmail: 'ducanh@lenfolk.vn',
    tags: ['bài tập', 'ngón tay'],
    viewCount: 1120,
    completionRate: 85,
    pathId: 'P001',
    pathTitle: 'Nhập môn sáo trúc',
    createdAt: '2026-03-10',
    updatedAt: '2026-04-20',
  },
  {
    id: 'L005',
    title: 'Lý thuyết âm nhạc cho sáo trúc',
    description:
      'Giới thiệu ký hiệu âm nhạc, thang âm và cách đọc bản nhạc sáo.',
    type: 'theory',
    level: 'intermediate',
    status: 'draft',
    duration: 30,
    author: 'GV. Lan Anh',
    authorEmail: 'lananh@lenfolk.vn',
    tags: ['lý thuyết', 'ký âm', 'thang âm'],
    viewCount: 0,
    completionRate: 0,
    pathId: 'P002',
    pathTitle: 'Nhạc lý và ký âm',
    createdAt: '2026-04-20',
    updatedAt: '2026-05-10',
  },
  {
    id: 'L006',
    title: 'Nhạc dân tộc: Lý Con Sáo',
    description: 'Hướng dẫn thổi bài dân ca "Lý Con Sáo" hoàn chỉnh.',
    type: 'video',
    level: 'intermediate',
    status: 'published',
    duration: 22,
    author: 'GV. Lan Anh',
    authorEmail: 'lananh@lenfolk.vn',
    tags: ['dân ca', 'nhạc dân tộc', 'tiết mục'],
    viewCount: 2341,
    completionRate: 68,
    pathId: 'P004',
    pathTitle: 'Tiết mục dân ca',
    createdAt: '2026-02-15',
    updatedAt: '2026-03-01',
  },
  {
    id: 'L007',
    title: 'Kỹ thuật rung ngón (Vibrato)',
    description: 'Học kỹ thuật rung ngón tạo âm thanh mềm mại và truyền cảm.',
    type: 'video',
    level: 'intermediate',
    status: 'archived',
    duration: 20,
    author: 'GV. Minh Tú',
    authorEmail: 'minhtu@lenfolk.vn',
    tags: ['vibrato', 'rung ngón', 'kỹ thuật'],
    viewCount: 650,
    completionRate: 55,
    pathId: 'P003',
    pathTitle: 'Kỹ thuật nâng cao',
    createdAt: '2026-01-10',
    updatedAt: '2026-02-28',
  },
  {
    id: 'L008',
    title: 'Bài tập hơi thổi dài',
    description: 'Luyện tập giữ hơi thổi dài và ổn định tone âm.',
    type: 'exercise',
    level: 'intermediate',
    status: 'draft',
    duration: 15,
    author: 'GV. Thu Hà',
    authorEmail: 'thuha@lenfolk.vn',
    tags: ['bài tập', 'hơi thổi'],
    viewCount: 0,
    completionRate: 0,
    createdAt: '2026-05-12',
    updatedAt: '2026-05-14',
  },
];

// ─── Learning Paths ───────────────────────────────────────────────────────────
export const MOCK_PATHS: LearningPath[] = [
  {
    id: 'P001',
    title: 'Nhập môn sáo trúc',
    description:
      'Lộ trình hoàn chỉnh dành cho người mới bắt đầu học sáo trúc từ con số 0.',
    category: 'foundation',
    level: 'beginner',
    status: 'published',
    totalLessons: 12,
    totalDuration: 180,
    enrolledCount: 589,
    completionRate: 72,
    instructor: 'GV. Minh Tú',
    lessonIds: ['L001', 'L002', 'L004'],
    createdAt: '2026-01-15',
    updatedAt: '2026-04-20',
  },
  {
    id: 'P002',
    title: 'Nhạc lý và ký âm sáo',
    description:
      'Nền tảng lý thuyết âm nhạc áp dụng chuyên biệt cho nhạc cụ sáo trúc.',
    category: 'foundation',
    level: 'beginner',
    status: 'published',
    totalLessons: 8,
    totalDuration: 130,
    enrolledCount: 312,
    completionRate: 65,
    instructor: 'GV. Lan Anh',
    lessonIds: ['L005'],
    createdAt: '2026-02-01',
    updatedAt: '2026-05-01',
  },
  {
    id: 'P003',
    title: 'Kỹ thuật nâng cao',
    description:
      'Các kỹ thuật thổi sáo chuyên sâu: láy hơi, vibrato, staccato.',
    category: 'technique',
    level: 'advanced',
    status: 'published',
    totalLessons: 10,
    totalDuration: 210,
    enrolledCount: 178,
    completionRate: 48,
    instructor: 'GV. Minh Tú',
    lessonIds: ['L003', 'L007'],
    createdAt: '2026-02-10',
    updatedAt: '2026-05-05',
  },
  {
    id: 'P004',
    title: 'Tiết mục dân ca Việt Nam',
    description:
      'Thực hành các bài dân ca nổi tiếng qua các vùng miền Việt Nam.',
    category: 'repertoire',
    level: 'intermediate',
    status: 'published',
    totalLessons: 15,
    totalDuration: 320,
    enrolledCount: 243,
    completionRate: 58,
    instructor: 'GV. Lan Anh',
    lessonIds: ['L006'],
    createdAt: '2026-01-20',
    updatedAt: '2026-04-15',
  },
  {
    id: 'P005',
    title: 'Kỹ thuật luyến láy',
    description:
      'Nghiên cứu chuyên sâu về kỹ thuật luyến láy trong âm nhạc dân tộc.',
    category: 'technique',
    level: 'intermediate',
    status: 'draft',
    totalLessons: 7,
    totalDuration: 140,
    enrolledCount: 0,
    completionRate: 0,
    instructor: 'GV. Thu Hà',
    lessonIds: [],
    createdAt: '2026-05-08',
    updatedAt: '2026-05-14',
  },
  {
    id: 'P006',
    title: 'Nhạc cổ điển Trung Hoa cho sáo',
    description:
      'Các tác phẩm nhạc cổ điển Trung Hoa được chuyển soạn cho sáo trúc Việt.',
    category: 'repertoire',
    level: 'advanced',
    status: 'draft',
    totalLessons: 9,
    totalDuration: 240,
    enrolledCount: 0,
    completionRate: 0,
    instructor: 'GV. Đức Anh',
    lessonIds: [],
    createdAt: '2026-05-13',
    updatedAt: '2026-05-14',
  },
];

// ─── Content Submissions ──────────────────────────────────────────────────────
export const MOCK_SUBMISSIONS: ContentSubmission[] = [
  {
    id: 'CS001',
    title: 'Kỹ thuật láy hơi nâng cao (v2)',
    type: 'lesson',
    author: 'GV. Minh Tú',
    authorEmail: 'minhtu@lenfolk.vn',
    submittedAt: '2026-05-16T08:30:00',
    status: 'pending',
    description: 'Phiên bản cập nhật với thêm ví dụ và bài tập thực hành.',
    duration: 28,
    level: 'advanced',
    previewUrl: 'https://example.com/preview/CS001',
  },
  {
    id: 'CS002',
    title: 'Lộ trình học sáo cho người mới – 2026',
    type: 'learning_path',
    author: 'GV. Thu Hà',
    authorEmail: 'thuha@lenfolk.vn',
    submittedAt: '2026-05-15T14:00:00',
    status: 'pending',
    description: 'Lộ trình cải tiến với nội dung cập nhật cho năm 2026.',
    level: 'beginner',
  },
  {
    id: 'CS003',
    title: 'Bài tập ngón tay số 3 – trung cấp',
    type: 'exercise',
    author: 'GV. Đức Anh',
    authorEmail: 'ducanh@lenfolk.vn',
    submittedAt: '2026-05-14T10:15:00',
    status: 'pending',
    description: 'Bài tập ngón tay nâng cao dành cho học viên trung cấp.',
    duration: 12,
    level: 'intermediate',
  },
  {
    id: 'CS004',
    title: 'Nhạc dân tộc: Bèo Dạt Mây Trôi',
    type: 'lesson',
    author: 'GV. Lan Anh',
    authorEmail: 'lananh@lenfolk.vn',
    submittedAt: '2026-05-13T09:00:00',
    status: 'approved',
    description: 'Hướng dẫn thổi bài dân ca nổi tiếng miền Bắc.',
    duration: 24,
    level: 'intermediate',
    reviewedAt: '2026-05-14T11:00:00',
    reviewedBy: 'Admin Nguyễn',
    commission: { rate: 30, basePrice: 199000, totalEarned: 4820000 },
  },
  {
    id: 'CS005',
    title: 'Staccato trong sáo trúc',
    type: 'lesson',
    author: 'GV. Minh Tú',
    authorEmail: 'minhtu@lenfolk.vn',
    submittedAt: '2026-05-10T08:00:00',
    status: 'approved',
    description: 'Kỹ thuật staccato và cách áp dụng trong các bài nhạc.',
    duration: 20,
    level: 'intermediate',
    reviewedAt: '2026-05-11T09:00:00',
    reviewedBy: 'Admin Nguyễn',
    commission: { rate: 30, basePrice: 199000, totalEarned: 3580000 },
  },
  {
    id: 'CS006',
    title: 'Lịch sử sáo trúc Việt Nam',
    type: 'lesson',
    author: 'GV. Lan Anh',
    authorEmail: 'lananh@lenfolk.vn',
    submittedAt: '2026-05-08T16:00:00',
    status: 'rejected',
    description: 'Nội dung lịch sử về sáo trúc qua các thời kỳ.',
    duration: 35,
    level: 'beginner',
    reviewedAt: '2026-05-09T10:00:00',
    reviewedBy: 'Admin Nguyễn',
    rejectionReason:
      'Nội dung thiếu tính thực hành. Vui lòng bổ sung các ví dụ âm thanh và bài tập thực tế.',
  },
  {
    id: 'CS007',
    title: 'Phân tích âm nhạc truyền thống',
    type: 'learning_path',
    author: 'GV. Thu Hà',
    authorEmail: 'thuha@lenfolk.vn',
    submittedAt: '2026-05-06T11:00:00',
    status: 'rejected',
    description: 'Phân tích chuyên sâu về âm nhạc truyền thống Việt Nam.',
    level: 'advanced',
    reviewedAt: '2026-05-07T15:00:00',
    reviewedBy: 'Admin Nguyễn',
    rejectionReason:
      'Lộ trình quá trùng lặp với nội dung hiện có. Cần tập trung vào điểm khác biệt rõ ràng hơn.',
  },
];

// ─── Curriculum (Learning Path lesson sequences) ──────────────────────────────
export const MOCK_CURRICULUM: CurriculumItem[] = [
  // Foundation track
  {
    id: 'CI001',
    track: 'foundation',
    order: 1,
    session: 'Buổi 1',
    title: 'Giới thiệu sáo trúc (6 lỗ) + cách cầm + đặt môi',
    type: 'lesson',
    description:
      'Giới thiệu cấu tạo sáo trúc, kỹ thuật cầm sáo (có minh họa), đặt môi (video + hình minh họa)',
  },
  {
    id: 'CI002',
    track: 'foundation',
    order: 2,
    session: 'Buổi 2',
    title: 'Đặt môi + tạo âm thanh',
    type: 'lesson',
    description: 'Thổi sáo để tạo âm thanh mà không bấm phím',
  },
  {
    id: 'CI003',
    track: 'foundation',
    order: 3,
    session: 'Buổi 3',
    title: 'Kỹ thuật bấm ngón và các nốt cơ bản (đô, rê, mi...)',
    type: 'lesson',
    description: 'Tài liệu, hình minh họa vị trí ngón tay',
  },
  {
    id: 'CI004',
    track: 'foundation',
    order: 4,
    session: 'Buổi 4',
    title: 'Luyện hơi — cách thở & tạo âm nốt cơ bản',
    type: 'lesson',
    description: 'Kỹ thuật thở đúng (thở bụng), đặt môi đúng, chỉ tạo âm thanh',
  },
  {
    id: 'CI005',
    track: 'foundation',
    order: 5,
    session: 'Buổi 4',
    title: 'Bài luyện tập 1.1 — Nốt tròn',
    type: 'exercise',
    description: 'Chỉ nốt tròn',
  },
  {
    id: 'CI006',
    track: 'foundation',
    order: 6,
    session: 'Buổi 5',
    title: 'Tạo các nốt cơ bản (si, la,... → đô)',
    type: 'lesson',
    description:
      'Hình minh họa ngón tay cho nốt Đô + AI nhận diện cao độ → Điều chỉnh',
  },
  {
    id: 'CI007',
    track: 'foundation',
    order: 7,
    session: 'Buổi 5',
    title: 'Bài luyện tập 2.1 — Nốt đen sol, la, si',
    type: 'exercise',
    description: 'Nốt đen: sol, la, si',
  },
  {
    id: 'CI008',
    track: 'foundation',
    order: 8,
    session: 'Buổi 5',
    title: 'Bài luyện tập 2.2 — Nốt đen đô, rê, mi, fa',
    type: 'exercise',
    description: 'Nốt đen: đô, rê, mi, fa',
  },
  // Technique track
  {
    id: 'CI101',
    track: 'technique',
    order: 1,
    session: 'Buổi 1',
    title: 'Kỹ thuật rung ngón (Vibrato)',
    type: 'lesson',
    description:
      'Rung ngón từ chậm đến nhanh, tạo âm thanh mềm mại và truyền cảm',
  },
  {
    id: 'CI102',
    track: 'technique',
    order: 2,
    session: 'Buổi 2',
    title: 'Kỹ thuật láy hơi cơ bản',
    type: 'lesson',
    description:
      'Láy hơi đôi, láy hơi đơn với tốc độ chậm — dùng AI nhận diện độ chính xác',
  },
  {
    id: 'CI103',
    track: 'technique',
    order: 3,
    session: 'Buổi 2',
    title: 'Bài tập láy hơi 1.1',
    type: 'exercise',
    description: 'Luyện tập láy hơi theo bài tập mẫu, tốc độ 60 BPM',
  },
  {
    id: 'CI104',
    track: 'technique',
    order: 4,
    session: 'Buổi 3',
    title: 'Kỹ thuật lưỡi kép (Double Tonguing)',
    type: 'lesson',
    description: 'Tu-ku, tu-ku — kỹ thuật articulation nhanh cho sáo trúc',
  },
  {
    id: 'CI105',
    track: 'technique',
    order: 5,
    session: 'Buổi 3',
    title: 'Bài tập lưỡi kép 2.1',
    type: 'exercise',
    description:
      'Bài tập lưỡi kép ở tốc độ 60–80 BPM, luyện đều tay và đều hơi',
  },
  {
    id: 'CI106',
    track: 'technique',
    order: 6,
    session: 'Buổi 4',
    title: 'Kỹ thuật glissando — trượt ngón',
    type: 'lesson',
    description:
      'Trượt ngón liên tục trên thang âm, tạo hiệu ứng âm thanh đặc sắc',
  },
  // Repertoire track
  {
    id: 'CI201',
    track: 'repertoire',
    order: 1,
    session: 'Buổi 1',
    title: 'Lý Con Sáo — bản hoàn chỉnh',
    type: 'lesson',
    description: 'Dân ca Nam Bộ, tempo vừa phải, phù hợp trình độ trung cấp',
  },
  {
    id: 'CI202',
    track: 'repertoire',
    order: 2,
    session: 'Buổi 2',
    title: 'Trống Cơm',
    type: 'lesson',
    description:
      'Dân ca Bắc Bộ, nhịp điệu đặc trưng, phức tạp hơn với các luyến láy',
  },
  {
    id: 'CI203',
    track: 'repertoire',
    order: 3,
    session: 'Buổi 2',
    title: 'Bài tập Trống Cơm đoạn A',
    type: 'exercise',
    description:
      'Luyện tập đoạn mở đầu với các luyến láy đặc trưng dân ca Bắc Bộ',
  },
  {
    id: 'CI204',
    track: 'repertoire',
    order: 4,
    session: 'Buổi 3',
    title: 'Bèo Dạt Mây Trôi',
    type: 'lesson',
    description: 'Dân ca Bắc Bộ, có kỹ thuật rung hơi và luyến nốt nâng cao',
  },
  {
    id: 'CI205',
    track: 'repertoire',
    order: 5,
    session: 'Buổi 4',
    title: 'Lưu Thủy Hành Vân',
    type: 'lesson',
    description:
      'Nhạc cổ điển Việt Nam, tempo chậm, thể hiện cảm xúc qua kỹ thuật vibrato',
  },
];
